"""Distributed lock model for global concurrency control."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from stardag_api.models.base import Base, utc_now

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from stardag_api.models.environment import Environment


class DistributedLock(Base):
    """Lease-based distributed lock for global task concurrency control.

    Locks are scoped to environment and identified by name (typically task_id).
    Uses TTL-based expiration for automatic cleanup on client failure.
    """

    __tablename__ = "distributed_locks"
    __table_args__ = (
        Index(
            "ix_distributed_locks_environment_expires", "environment_id", "expires_at"
        ),
        Index("ix_distributed_locks_expires", "expires_at"),
    )

    # Lock name is the primary key (typically: task_id)
    name: Mapped[str] = mapped_column(Text, primary_key=True)

    # Environment scope
    environment_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("environments.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Owner identification (UUID generated by client, stable across retries)
    owner_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False).with_variant(String(36), "sqlite"),
        nullable=False,
    )

    # Timestamps
    acquired_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utc_now,
        nullable=False,
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )

    # Version for optimistic locking (incremented on each renewal)
    version: Mapped[int] = mapped_column(
        BigInteger,
        default=0,
        nullable=False,
    )

    # Relationships
    environment: Mapped[Environment] = relationship()
