"""add created_by_id to organizations

Revision ID: 8a2a0c6c2c26
Revises: 001_normalized
Create Date: 2025-12-21 02:11:10.017136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a2a0c6c2c26"
down_revision: Union[str, Sequence[str], None] = "001_normalized"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("created_by_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_organizations_created_by_id"),
        "organizations",
        ["created_by_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "organizations", "users", ["created_by_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organizations", type_="foreignkey")
    op.drop_index(op.f("ix_organizations_created_by_id"), table_name="organizations")
    op.drop_column("organizations", "created_by_id")
    # ### end Alembic commands ###
