"""add is_personal to workspace

Revision ID: 0e0322b9f402
Revises: 3cf2e4b9b2d2
Create Date: 2026-01-19 20:03:40.606736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e0322b9f402"
down_revision: Union[str, Sequence[str], None] = "3cf2e4b9b2d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspaces",
        sa.Column("is_personal", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "is_personal")
    # ### end Alembic commands ###
