"""initial schema

Revision ID: 8125a7f4f1ff
Revises: 
Create Date: 2026-01-05 23:08:47.875028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8125a7f4f1ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_by_id'), 'organizations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='organizationrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', name='invitestatus'), nullable=False),
    sa.Column('invited_by_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invite_org_email_pending', 'invites', ['organization_id', 'email'], unique=True, postgresql_where="status = 'pending'")
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_index(op.f('ix_invites_organization_id'), 'invites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invites_status'), 'invites', ['status'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='organizationrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_workspace_org_slug')
    )
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_revoked_at'), 'api_keys', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('root_task_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_commit_hash'), 'builds', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_builds_name'), 'builds', ['name'], unique=False)
    op.create_index(op.f('ix_builds_user_id'), 'builds', ['user_id'], unique=False)
    op.create_index('ix_builds_workspace_created', 'builds', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_builds_workspace_id'), 'builds', ['workspace_id'], unique=False)
    op.create_table('target_roots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri_prefix', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_target_root_workspace_name')
    )
    op.create_index(op.f('ix_target_roots_workspace_id'), 'target_roots', ['workspace_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('task_namespace', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_data', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'task_id', name='uq_task_workspace_taskid')
    )
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_name'), 'tasks', ['task_name'], unique=False)
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    op.create_index('ix_tasks_workspace_name', 'tasks', ['workspace_id', 'task_name'], unique=False)
    op.create_index('ix_tasks_workspace_namespace', 'tasks', ['workspace_id', 'task_namespace'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('build_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_build_created', 'events', ['build_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_build_id'), 'events', ['build_id'], unique=False)
    op.create_index('ix_events_build_task_type', 'events', ['build_id', 'task_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index('ix_events_task_created', 'events', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_task_id'), 'events', ['task_id'], unique=False)
    op.create_index('ix_events_type_created', 'events', ['event_type', 'created_at'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upstream_task_id', sa.Integer(), nullable=False),
    sa.Column('downstream_task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['downstream_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upstream_task_id', 'downstream_task_id', name='uq_task_dependency_edge')
    )
    op.create_index('ix_task_dep_downstream', 'task_dependencies', ['downstream_task_id'], unique=False)
    op.create_index('ix_task_dep_upstream', 'task_dependencies', ['upstream_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_dep_upstream', table_name='task_dependencies')
    op.drop_index('ix_task_dep_downstream', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('ix_events_type_created', table_name='events')
    op.drop_index(op.f('ix_events_task_id'), table_name='events')
    op.drop_index('ix_events_task_created', table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index('ix_events_build_task_type', table_name='events')
    op.drop_index(op.f('ix_events_build_id'), table_name='events')
    op.drop_index('ix_events_build_created', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_tasks_workspace_namespace', table_name='tasks')
    op.drop_index('ix_tasks_workspace_name', table_name='tasks')
    op.drop_index(op.f('ix_tasks_workspace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_target_roots_workspace_id'), table_name='target_roots')
    op.drop_table('target_roots')
    op.drop_index(op.f('ix_builds_workspace_id'), table_name='builds')
    op.drop_index('ix_builds_workspace_created', table_name='builds')
    op.drop_index(op.f('ix_builds_user_id'), table_name='builds')
    op.drop_index(op.f('ix_builds_name'), table_name='builds')
    op.drop_index(op.f('ix_builds_commit_hash'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_revoked_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_invites_status'), table_name='invites')
    op.drop_index(op.f('ix_invites_organization_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_index('ix_invite_org_email_pending', table_name='invites', postgresql_where="status = 'pending'")
    op.drop_table('invites')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_by_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
