"""remove unique constraint from workspace name

Revision ID: 941cd8b749c7
Revises: 4f69a5df4d93
Create Date: 2026-02-02 11:25:15.168048

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "941cd8b749c7"
down_revision: Union[str, Sequence[str], None] = "4f69a5df4d93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspaces_name"), table_name="workspaces")
    op.create_index(op.f("ix_workspaces_name"), "workspaces", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspaces_name"), table_name="workspaces")
    op.create_index(op.f("ix_workspaces_name"), "workspaces", ["name"], unique=True)
    # ### end Alembic commands ###
