"""add tasks.latest_status_expires_at (execution claim expiry)

Nullable with no backfill and no index, deliberately. NULL is the pre-expiry
semantic — "this claim never lapses" — so every existing row keeps behaving
exactly as it does today, and the column starts mattering only for claims
granted after the deploy. Every reader narrows on latest_status first, so the
expiry is a comparison over the few RUNNING rows that survive that.

Revision ID: f6a5873c30fb
Revises: 11716b1f4c1a
Create Date: 2026-08-07 23:31:50.581651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6a5873c30fb"
down_revision: Union[str, Sequence[str], None] = "11716b1f4c1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "latest_status_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "latest_status_expires_at")
    # ### end Alembic commands ###
