"""add concurrency limit tables

Revision ID: 02fd1dc17202
Revises: aef9ba956f51
Create Date: 2026-07-12 08:22:23.206470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02fd1dc17202"
down_revision: Union[str, Sequence[str], None] = "aef9ba956f51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environment_concurrency_limits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("max_concurrent", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "environment_id", "key", name="uq_environment_concurrency_limit_key"
        ),
    )
    op.create_index(
        op.f("ix_environment_concurrency_limits_environment_id"),
        "environment_concurrency_limits",
        ["environment_id"],
        unique=False,
    )
    op.create_table(
        "task_limit_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_pk", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["task_pk"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_pk", "key", name="uq_task_limit_key"),
    )
    op.create_index("ix_task_limit_keys_key", "task_limit_keys", ["key"], unique=False)
    op.create_index(
        op.f("ix_task_limit_keys_task_pk"), "task_limit_keys", ["task_pk"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_limit_keys_task_pk"), table_name="task_limit_keys")
    op.drop_index("ix_task_limit_keys_key", table_name="task_limit_keys")
    op.drop_table("task_limit_keys")
    op.drop_index(
        op.f("ix_environment_concurrency_limits_environment_id"),
        table_name="environment_concurrency_limits",
    )
    op.drop_table("environment_concurrency_limits")
    # ### end Alembic commands ###
