"""add is_dynamic column to task_dependencies

Revision ID: 94003640952d
Revises: f012cf09483c
Create Date: 2026-04-20 16:26:10.976338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94003640952d"
down_revision: Union[str, Sequence[str], None] = "f012cf09483c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_dependencies",
        sa.Column("is_dynamic", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_dependencies", "is_dynamic")
    # ### end Alembic commands ###
