"""add task latest executor ref columns

Revision ID: 18af8e5ee48a
Revises: c1ea60e468b8
Create Date: 2026-07-12 00:36:24.345528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18af8e5ee48a"
down_revision: Union[str, Sequence[str], None] = "c1ea60e468b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("latest_executor", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "tasks", sa.Column("latest_executor_ref", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "latest_executor_ref")
    op.drop_column("tasks", "latest_executor")
    # ### end Alembic commands ###
