"""add distributed_locks table and workspace max_concurrent_locks

Revision ID: 43245b5116be
Revises: c038d474b347
Create Date: 2026-01-11 14:39:20.582803

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43245b5116be"
down_revision: Union[str, Sequence[str], None] = "c038d474b347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributed_locks",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column(
            "owner_id",
            sa.UUID(as_uuid=False).with_variant(sa.String(length=36), "sqlite"),
            nullable=False,
        ),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(
        "ix_distributed_locks_expires",
        "distributed_locks",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_distributed_locks_workspace_expires",
        "distributed_locks",
        ["workspace_id", "expires_at"],
        unique=False,
    )
    op.add_column(
        "workspaces", sa.Column("max_concurrent_locks", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "max_concurrent_locks")
    op.drop_index(
        "ix_distributed_locks_workspace_expires", table_name="distributed_locks"
    )
    op.drop_index("ix_distributed_locks_expires", table_name="distributed_locks")
    op.drop_table("distributed_locks")
    # ### end Alembic commands ###
