"""add task_registry_assets table

Revision ID: c038d474b347
Revises: 8125a7f4f1ff
Create Date: 2026-01-06 20:43:26.358547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c038d474b347"
down_revision: Union[str, Sequence[str], None] = "8125a7f4f1ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_registry_assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_pk", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("body_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_pk"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "task_pk",
            "asset_type",
            "name",
            name="uq_task_registry_asset_task_type_name",
        ),
    )
    op.create_index(
        "ix_task_registry_assets_task_pk",
        "task_registry_assets",
        ["task_pk"],
        unique=False,
    )
    op.create_index(
        "ix_task_registry_assets_workspace",
        "task_registry_assets",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_task_registry_assets_workspace", table_name="task_registry_assets"
    )
    op.drop_index("ix_task_registry_assets_task_pk", table_name="task_registry_assets")
    op.drop_table("task_registry_assets")
    # ### end Alembic commands ###
