"""add executor metadata columns

Revision ID: 966bad447840
Revises: 02fd1dc17202
Create Date: 2026-07-13 12:43:58.949808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "966bad447840"
down_revision: Union[str, Sequence[str], None] = "02fd1dc17202"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "builds",
        sa.Column(
            "executor_metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "latest_executor_metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "latest_executor_metadata")
    op.drop_column("builds", "executor_metadata")
    # ### end Alembic commands ###
