"""add build needs_tick_at

Revision ID: aef9ba956f51
Revises: 18af8e5ee48a
Create Date: 2026-07-12 01:43:29.525318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aef9ba956f51"
down_revision: Union[str, Sequence[str], None] = "18af8e5ee48a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "builds", sa.Column("needs_tick_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("builds", "needs_tick_at")
    # ### end Alembic commands ###
