"""initial schema with uuid7

Revision ID: 4f69a5df4d93
Revises:
Create Date: 2026-01-29 22:40:07.255201

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f69a5df4d93"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_external_id"), "users", ["external_id"], unique=True)
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("is_personal", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspaces_created_by_id"),
        "workspaces",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(op.f("ix_workspaces_name"), "workspaces", ["name"], unique=True)
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_table(
        "environments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("max_concurrent_locks", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "slug", name="uq_environment_workspace_slug"
        ),
    )
    op.create_index(
        op.f("ix_environments_owner_id"), "environments", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_environments_slug"), "environments", ["slug"], unique=False
    )
    op.create_index(
        op.f("ix_environments_workspace_id"),
        "environments",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "member", name="workspacerole"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "accepted", "declined", "cancelled", name="invitestatus"
            ),
            nullable=False,
        ),
        sa.Column("invited_by_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["invited_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invite_workspace_email_pending",
        "invites",
        ["workspace_id", "email"],
        unique=True,
        postgresql_where="status = 'pending'",
    )
    op.create_index(op.f("ix_invites_email"), "invites", ["email"], unique=False)
    op.create_index(op.f("ix_invites_status"), "invites", ["status"], unique=False)
    op.create_index(
        op.f("ix_invites_workspace_id"), "invites", ["workspace_id"], unique=False
    )
    op.create_table(
        "workspace_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "member", name="workspacerole"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id", name="uq_workspace_member"),
    )
    op.create_index(
        op.f("ix_workspace_members_user_id"),
        "workspace_members",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_members_workspace_id"),
        "workspace_members",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=8), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_keys_environment_id"), "api_keys", ["environment_id"], unique=False
    )
    op.create_index(
        op.f("ix_api_keys_key_prefix"), "api_keys", ["key_prefix"], unique=False
    )
    op.create_index(
        op.f("ix_api_keys_revoked_at"), "api_keys", ["revoked_at"], unique=False
    )
    op.create_table(
        "builds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("commit_hash", sa.String(length=64), nullable=True),
        sa.Column("root_task_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_builds_commit_hash"), "builds", ["commit_hash"], unique=False
    )
    op.create_index(
        "ix_builds_environment_created",
        "builds",
        ["environment_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_builds_environment_id"), "builds", ["environment_id"], unique=False
    )
    op.create_index(op.f("ix_builds_name"), "builds", ["name"], unique=False)
    op.create_index(op.f("ix_builds_user_id"), "builds", ["user_id"], unique=False)
    op.create_table(
        "distributed_locks",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "owner_id",
            sa.Uuid().with_variant(sa.String(length=36), "sqlite"),
            nullable=False,
        ),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(
        "ix_distributed_locks_environment_expires",
        "distributed_locks",
        ["environment_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_distributed_locks_expires",
        "distributed_locks",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "target_roots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("uri_prefix", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "environment_id", "name", name="uq_target_root_environment_name"
        ),
    )
    op.create_index(
        op.f("ix_target_roots_environment_id"),
        "target_roots",
        ["environment_id"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("task_namespace", sa.String(length=255), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("task_data", sa.JSON(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("output_uri", sa.String(length=2048), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "environment_id", "task_id", name="uq_task_environment_taskid"
        ),
    )
    op.create_index(
        op.f("ix_tasks_environment_id"), "tasks", ["environment_id"], unique=False
    )
    op.create_index(
        "ix_tasks_environment_name",
        "tasks",
        ["environment_id", "task_name"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_environment_namespace",
        "tasks",
        ["environment_id", "task_namespace"],
        unique=False,
    )
    op.create_index(op.f("ix_tasks_task_id"), "tasks", ["task_id"], unique=False)
    op.create_index(op.f("ix_tasks_task_name"), "tasks", ["task_name"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("build_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["build_id"], ["builds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_events_build_created", "events", ["build_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_events_build_id"), "events", ["build_id"], unique=False)
    op.create_index(
        "ix_events_build_task_type",
        "events",
        ["build_id", "task_id", "event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_events_created_at"), "events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_events_event_type"), "events", ["event_type"], unique=False
    )
    op.create_index(
        "ix_events_task_created", "events", ["task_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_events_task_id"), "events", ["task_id"], unique=False)
    op.create_index(
        "ix_events_type_created", "events", ["event_type", "created_at"], unique=False
    )
    op.create_table(
        "task_dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("upstream_task_id", sa.Uuid(), nullable=False),
        sa.Column("downstream_task_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["downstream_task_id"], ["tasks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["upstream_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "upstream_task_id", "downstream_task_id", name="uq_task_dependency_edge"
        ),
    )
    op.create_index(
        "ix_task_dep_downstream",
        "task_dependencies",
        ["downstream_task_id"],
        unique=False,
    )
    op.create_index(
        "ix_task_dep_upstream", "task_dependencies", ["upstream_task_id"], unique=False
    )
    op.create_table(
        "task_registry_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_pk", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("body_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["task_pk"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "task_pk",
            "asset_type",
            "name",
            name="uq_task_registry_asset_task_type_name",
        ),
    )
    op.create_index(
        "ix_task_registry_assets_environment",
        "task_registry_assets",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        "ix_task_registry_assets_task_pk",
        "task_registry_assets",
        ["task_pk"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_registry_assets_task_pk", table_name="task_registry_assets")
    op.drop_index(
        "ix_task_registry_assets_environment", table_name="task_registry_assets"
    )
    op.drop_table("task_registry_assets")
    op.drop_index("ix_task_dep_upstream", table_name="task_dependencies")
    op.drop_index("ix_task_dep_downstream", table_name="task_dependencies")
    op.drop_table("task_dependencies")
    op.drop_index("ix_events_type_created", table_name="events")
    op.drop_index(op.f("ix_events_task_id"), table_name="events")
    op.drop_index("ix_events_task_created", table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_index("ix_events_build_task_type", table_name="events")
    op.drop_index(op.f("ix_events_build_id"), table_name="events")
    op.drop_index("ix_events_build_created", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_tasks_task_name"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_task_id"), table_name="tasks")
    op.drop_index("ix_tasks_environment_namespace", table_name="tasks")
    op.drop_index("ix_tasks_environment_name", table_name="tasks")
    op.drop_index(op.f("ix_tasks_environment_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_target_roots_environment_id"), table_name="target_roots")
    op.drop_table("target_roots")
    op.drop_index("ix_distributed_locks_expires", table_name="distributed_locks")
    op.drop_index(
        "ix_distributed_locks_environment_expires", table_name="distributed_locks"
    )
    op.drop_table("distributed_locks")
    op.drop_index(op.f("ix_builds_user_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_name"), table_name="builds")
    op.drop_index(op.f("ix_builds_environment_id"), table_name="builds")
    op.drop_index("ix_builds_environment_created", table_name="builds")
    op.drop_index(op.f("ix_builds_commit_hash"), table_name="builds")
    op.drop_table("builds")
    op.drop_index(op.f("ix_api_keys_revoked_at"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_environment_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(
        op.f("ix_workspace_members_workspace_id"), table_name="workspace_members"
    )
    op.drop_index(op.f("ix_workspace_members_user_id"), table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_index(op.f("ix_invites_workspace_id"), table_name="invites")
    op.drop_index(op.f("ix_invites_status"), table_name="invites")
    op.drop_index(op.f("ix_invites_email"), table_name="invites")
    op.drop_index(
        "ix_invite_workspace_email_pending",
        table_name="invites",
        postgresql_where="status = 'pending'",
    )
    op.drop_table("invites")
    op.drop_index(op.f("ix_environments_workspace_id"), table_name="environments")
    op.drop_index(op.f("ix_environments_slug"), table_name="environments")
    op.drop_index(op.f("ix_environments_owner_id"), table_name="environments")
    op.drop_table("environments")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_name"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_created_by_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_users_external_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
