"""add build reactive_meta

Revision ID: d31ca54ec8ab
Revises: 966bad447840
Create Date: 2026-07-14 01:13:26.947962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d31ca54ec8ab"
down_revision: Union[str, Sequence[str], None] = "966bad447840"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "builds",
        sa.Column(
            "reactive_meta",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("builds", "reactive_meta")
    # ### end Alembic commands ###
