"""add output_uri to tasks

Revision ID: 3cf2e4b9b2d2
Revises: 467b15c7fd1d
Create Date: 2026-01-16 14:24:53.105214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cf2e4b9b2d2"
down_revision: Union[str, Sequence[str], None] = "467b15c7fd1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("output_uri", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "output_uri")
    # ### end Alembic commands ###
