"""add tasks (environment_id, latest_status, latest_status_at) index

Revision ID: 11716b1f4c1a
Revises: 792fb8ab3c3c
Create Date: 2026-08-07 21:13:48.480923

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "11716b1f4c1a"
down_revision: Union[str, Sequence[str], None] = "792fb8ab3c3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tasks_environment_status",
        "tasks",
        ["environment_id", "latest_status", "latest_status_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_environment_status", table_name="tasks")
    # ### end Alembic commands ###
