"""add builds.tick_requested_at (wake hand-out mark)

One nullable column. Written by ``POST /builds/wake-candidates`` when it
hands a flagged build to a caller that will spawn its tick, and by
``POST /builds/{id}/notify`` when it tells a worker no scheduler is live.
Read by wake-candidates to skip builds handed out within the last window,
so N concurrent schedulers produce one tick per flagged build, not N.

No index and no backfill: the only reader also filters on the environment,
RUNNING status and a set ``needs_tick_at``, which the existing
``ix_builds_environment_status`` already narrows to a handful of rows, and
NULL is the correct starting value ("never handed out").

Revision ID: 97ce4e3cbf32
Revises: e87efdab31ca
Create Date: 2026-08-29 23:56:28.980291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97ce4e3cbf32"
down_revision: Union[str, Sequence[str], None] = "e87efdab31ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "builds",
        sa.Column("tick_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("builds", "tick_requested_at")
    # ### end Alembic commands ###
